version: "3.9"

services:
  api:
    image: madtomy/jobscraper-api:latest
    container_name: jobscraper-api
    ports:
      - "8000:8000"
    environment:
      # --- App configuration ---
      APP_ENV: production
      APP_NAME: JobScraper API
      APP_PORT: 8000
      LOG_LEVEL: "INFO"
      LOG_JSON: "true"

      # --- Database Configuration ---
      #DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: "jobs"
      DB_PASSWORD: "jobs_pw"
      DB_NAME: "jobsdb"
      DB_POOL_SIZE: 10
      DB_POOL_MAX_OVERFLOW: 20
    restart: unless-stopped

